Specialisterne/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pipkin/', include('pipkin.urls', namespace = 'pipkin') ),
]

pipkin/urls.py
from django.conf.urls import url


from . import views

app_name = 'pipkin'
urlpatterns = [
    # example: /pipkin/
    url(r'^$', views.index, name='index'),
    url(r'^persons/$', views.PersonsListView.as_view(), name='persons'),
    url(r'^person/(?P<pk>[0-9]+)$', views.PersonDetailView.as_view(), name='person'),
]

pipkin/models.py
from django.db import models
import datetime
from django import forms
from django.core.urlresolvers import reverse
# Create your models here.


class Person(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    INTER = 'X'

    SEX_CHOICES = (
                  (MALE, 'männlich'),
                  (FEMALE, 'weiblich'),
                  (INTER, 'inter'),
    )

    firstname = models.CharField('Vorname', blank=False, max_length=100)
    name = models.CharField('Nachname', blank=False, max_length=100)
    aliasName = models.CharField(
        'Alias-Name', blank=True, max_length=100)
    akdmTitle = models.CharField('Akadem. Titel', blank=True, max_length=50)
    sex = models.CharField('Geschlecht', max_length=1,
                           choices=SEX_CHOICES, default=INTER)
    birthday = models.DateField(
        'Geburtsdatum', default=datetime.date(1900, 1, 1))

    email = models.EmailField('Email', max_length=50, blank=True)
    telefon = models.CharField('Telefon', max_length=15, blank=True)

    sv = models.IntegerField('SV#', blank=True)

    # Technische Felder
    token = models.CharField(blank=True, max_length=6)

    created = models.DateTimeField(
        'Angelegt am', blank=False, auto_now_add=True)
    modified = models.DateTimeField('Geändert am', blank=False, auto_now=True)

    def __str__(self):
        output = self.firstname

        if(bool(self.aliasName)):
            output += ' "' + self.aliasName + '" '
        else:
            output += ' '

        output += self.name

        return output

    def person_display(self):
        return self

    person_display.short_description = 'Person'

    def get_absolute_url(self):
        return reverse('pipkin:person', args=[str(self.id)])


class Address(models.Model):
    MAIN = 'M'
    SIDE = 'S'

    TYPES_CHOICES = ((MAIN, 'Hauptadresse'), (SIDE, 'Nebenadresse'), )

    addressLine = models.CharField('Adresse', max_length=100, blank=False)
    addressType = models.CharField(
        'Type', max_length=1, choices=TYPES_CHOICES, default=MAIN)
    zipCode = models.CharField('PLZ', max_length=6, blank=False)
    city = models.CharField('Ort', max_length=30, blank=False)
    country = models.CharField('Land', max_length=50, blank=True)

    person = models.ForeignKey(Person)

    def __str__(self):
        return self.addressLine + ' , ' + self.zipCode + ' , ' + self.city


class Contact(models.Model):
    MAIN = 'M'
    SIDE = 'S'
    EMERCENCY = 'E'

    MAIL = 'M'
    PHONE = 'P'

    SEVERITY_CHOICES = ((MAIN, 'Hauptkontakt'),
                        (SIDE, 'Nebenkontakt'), (EMERCENCY, 'Notfallskontakt'))
    TYPE_CHOICES = ((MAIL, 'Email'), (PHONE, 'Telefon'))

    contactSeverity = models.CharField(
        'Dringlichkeit', max_length=1, choices=SEVERITY_CHOICES, default=MAIN, help_text='Zeigt die Relevanz des Kontakts'
        )
    contactType = models.CharField(
        'Type', max_length=1, choices=TYPE_CHOICES, default=MAIN)
    contactData = models.CharField('Kontaktdaten', max_length=200)
    spaContact = models.BooleanField('SPA Kontak', default=False)
    person = models.ForeignKey(Person)

    class Meta:
    	ordering: ["contactSeverity"]

class Tag(models.Model):
    tagName = models.CharField('Tag', max_length=50, blank=False)
    tagCategory = models.CharField('Kategorie', max_length=50, blank=False)





class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['addressType', 'addressLine', 'zipCode', 'city', 'country']
        widgets = {
            'zipCode': forms.TextInput(attrs={'size': 7}),
            'city': forms.TextInput(attrs={'size': 30})
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['contactSeverity', 'contactType',
                  'contactData', 'spaContact']
        widgets = {
            'contactData': forms.Textarea(attrs={'rows': 4, 'col': 50})
        }

pipkin/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.views import generic

from .models import Person


def index(request):
    num_person = Person.objects.all().count()
    latestAdded = Person.objects.latest('created')
    latestUpdated = Person.objects.latest('modified')

    return render(
        request,
        'pipkin/index.html',
        context={'num_person': num_person,
                 'latestAddedPerson': latestAdded,
                 'latestUpdatedPerson': latestUpdated
                 },
    )


class PersonsListView(generic.ListView):
    model = Person
    template_name = 'pipkin/person_list.html'
    context_object_name = 'my_person_list'
    queryset = Person.objects.all()


class PersonDetailView(generic.DetailView):
    model = Person
    template_name = 'pipkin/person.html'

pipkin/templates/pipkin/base_generic.html
<!DOCTYPE html>
<html lang="de">
<head>
  
  {% block title %}<title>Pipkin Database</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'pipkin:index' %}">Home</a></li>
          <li><a href="{% url 'pipkin:persons'%}">All persons</a></li>
          <li><a href="">All tags</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

pipkin/templates/pipkin/index.html
{% extends "pipkin/base_generic.html" %}

{% block content %}

    <h1>Pipkin Database</h1>

    <p>Welcome to <em>Pipkin Database</em>, a very basic website developed as a protoype.</p>
    
    <h2>Dashboard</h2>
    <p>Database Summary</p>
    <ul>
    	<li>Persons in DB: {{num_person}}</li>
    	<li>Latest added Person: {{latestAddedPerson}}</li>
    	<li>Latest updated Person: {{latestUpdatedPerson}}</li>
    </ul>


{% endblock %}

pipkin/templates/pipkin/person.html
{% extends 'pipkin/base_generic.html' %}

{% block content %}




{% endblock %}

pipkin/templates/pipkin/person_list.html
{% extends 'pipkin/base_generic.html' %}

{% block content %}


   <h2>All Persons listed</h2>
   {% if my_person_list %}

   <ul>
   
       {% for person in my_person_list %}

        <li> <a href="{{ person.get_absolute_url }}">{{person}}</a> </li>

       {% endfor %}
   </ul>

   {% endif %}

{% endblock %}